### PR TITLE
perf: improve `process` speed for residue based graph building

### PR DESCRIPTION
**Pull request by cbaakman**
This change makes sure that the `build_residue_graph` function spends a factor ~20 less time in building a residue graph, by reducing the number of iterations in python code and moving those to numpy implementation.

### CODE REVIEW

**Comment by gcroci2** [comment]
Tests are failing, could you fix them? @cbaakman

**Comment by cbaakman** [comment]
I see tests fail on importing pytorch. There seems to be some library missing: libcufft

This has nothing to do with the changes in this pull request.

How can we fix this?

**Comment by gcroci2** [comment]
> I see tests fail on importing pytorch. There seems to be some library missing: libcufft
> 
> This has nothing to do with the changes in this pull request.
> 
> How can we fix this?

Actually, tests on the main branch pass on my local env, while tests on this branch still don't (I just run them):
image

**Comment by cbaakman** [comment]
> > I see tests fail on importing pytorch. There seems to be some library missing: libcufft
> > This has nothing to do with the changes in this pull request.
> > How can we fix this?
> 
> Actually, tests on the main branch pass on my local env, while tests on this branch still don't (I just run them): image

Did you pull in the latest commit on this branch?

**Comment by gcroci2** [comment]
> > > I see tests fail on importing pytorch. There seems to be some library missing: libcufft
> > > This has nothing to do with the changes in this pull request.
> > > How can we fix this?
> > 
> > 
> > Actually, tests on the main branch pass on my local env, while tests on this branch still don't (I just run them): image
> 
> Did you pull in the latest commit on this branch?

Yes:

image

**Comment by cbaakman** [comment]
@gcroci2  I fixed the two issues, that you were encountering.

I still see the same missing libcufft library error on the github console, however.
I have no idea how to fix this.

**Comment by gcroci2** [comment]
> @gcroci2 I fixed the two issues, that you were encountering.
> 
> I still see the same missing libcufft library error on the github console, however. I have no idea how to fix this.

Something may have changed in the dependencies these days. I'll give a look at it this afternoon

**Comment by gcroci2** [comment]
In the CI we were installing PyTorch with CUDA support, but the GitHub-hosted runners don’t have GPUs: [About GitHub-hosted runners - GitHub Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). So after installation PyTorch was trying to import CUDA libraries, which are not installed through the CI. Weird that it wasn't failing before though.

I found that we could use a self-hosted runner: [About self-hosted runners - GitHub Docs](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners), but I don't know much about them. I'll ask my colleagues.

**Review by gcroci2 — APPROVED** [review]

**Pull request merged**
